CREATE DATABASE DBENGLISH
GO
USE DBENGLISH
GO

Drop TABLE Phrases
DROP TABLE Translations
DROP TABLE Users
DROP TABLE UserQuestions

CREATE TABLE Phrases (
	PhraseId	INT NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	Text		NVARCHAR(300) NOT NULL
)

CREATE TABLE Translations (
	TranslationId	INT NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	PhraseId		INT NOT NULL REFERENCES Phrases(PhraseId),
	Text			NVARCHAR(300) NOT NULL
)

CREATE INDEX idxPhraseId ON Translations(PhraseId)

CREATE TABLE Users (
	UserId		INT NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	Name		NVARCHAR(30) NOT NULL
)

CREATE TABLE UserQuestions (
	UserId			INT NOT NULL REFERENCES Users(UserId),
	PhraseId		INT NOT NULL REFERENCES Phrases(PhraseId),
	Difficulty		INT NOT NULL DEFAULT (200),
	PRIMARY KEY CLUSTERED (UserId, PhraseId)
)

CREATE INDEX idxPhraseId ON UserQuestions(PhraseId)
CREATE INDEX idxUserId ON UserQuestions(UserId)
